ansible-collections/community.hashi_vault

plugins/lookup/hashi_vault.py

Most of this PR sets the stage for addressing the issues related to #10 and tracked in https://github.com/ansible-collections/community.hashi_vault/projects/1 .
Most of those will be addressable now by adding new entries to the `LOW_PRECEDENCE_ENV_VAR_OPTIONS` var if they need such a thing (the rest are just argspec `env:` replacements).
The change here sets that up, and moves that functionality for `token_path`'s `$HOME` env var into that (as it's the only option already using such a thing). As such it doesn't change the functionality or user interface, just the implementation.
This PR also fixes #13 by forcing the hvac client to logout when not doing token auth. 
This also doesn't change any current functionality, it just helps prevent auth methods from inadvertently not assigning their …

hashi_vault - internal changes for env var processing and unwanted token loading fix

---

changelogs/fragments/27-add-hashi_vault-header_value-param.yml
plugins/lookup/hashi_vault.py

Add support for the optional parameter iam_server_id.  The value is used for the X-Vault-AWS-IAM-Server-ID header as part of GetCallerIdentity request.
hashi_vault
Without this feature the following would fail when the Hashi Vault policy requires the X-Vault-AWS-IAM-Server-ID header.
```
- name: Authenticate with a Vault app role
ansible.builtin.debug:
msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/test:hello auth_method=aws_iam_login role_id=ec2-instance url=https://vault-fqdn region=us-west-2') }}"
```
Including the parameter header_value will pass the value along to the HVAC library, which then sends it along as the header. This would return the secret.
```
- name: Authenticate with a Vault app role
ansible.builtin.debug:
msg: "{{ …
```

Add parameter to support X-Vault-AWS-IAM-Server-ID

---

.github/workflows/ansible-test.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/defaults/main.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/files/bin/.gitignore
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/handlers/main.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/meta/main.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/vault_download.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/vault_server.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/vars/.gitignore
tests/integration/targets/lookup_hashi_vault/playbooks/download_vault.yml
tests/integration/targets/lookup_hashi_vault/playbooks/test_lookup_hashi_vault.yml

**Tests**
- Reorganized the parts of tests dedicated to downloading Vault and starting a Vault server to be more discrete
- Vault download / extraction happens in the role's `files/bin` directory now (`.gitignored`), more on that later
- Download is skipped if the requested version of the binary already exists, saving the download and extraction steps
- Playbook added that calls just the Vault download portion of the role
- Vars related to vault version and location are moved to `defaults/` to better control overriding them and so that they are available to all role entry points
- Download Vault binaries directly from hashiCorp's releases server
- "Default" version of Vault to be tested against is now 1.6.0, the current latest release.
**CI**
- Some deduping of vars and paths by setting …

CI/Tests - Caching, multiple vault versions, etc.

---

changelogs/fragments/25-non-breaking-env-parameter-changes.yml
plugins/lookup/hashi_vault.py

Resolves #14 
- Add `ANSIBLE_HASHI_VAULT_NAMESPACE` env var to argspec
- Move `VAULT_NAMESPACE` env var to `LOW_PRECEDENCE_ENV_VAR_OPTIONS`
- Add new INI option for `namespace`
Resolves #16 
- Add `ANSIBLE_HASHI_VAULT_TOKEN` env var in argspec
- Move `VAULT_TOKEN` env var to `LOW_PRECEDENCE_ENV_VAR_OPTIONS`
These changes are non-breaking (see issues for detailed explanation).
hashi_vault.py
Overall project: https://github.com/ansible-collections/community.hashi_vault/projects/1
See also: #10

hashi_vault - parameter env var changes for token and namespace

---

changelogs/fragments/22-hashi_vault-aws_iam_login-mount_point.yml
plugins/lookup/hashi_vault.py

Fixes #7  
- Allows use of `mount_point` with `aws_iam_auth`
hashi_vault.py

hashi_vault - add support for using mount_point with aws_iam_login auth

---

changelogs/fragments/33-approle-deprecation.yml
plugins/lookup/hashi_vault.py

Fixes #32 
This started out just being a PR to use the newer hvac auth method class for AppRole, and add our deprecation fallback logic.
But I discovered that logic (which I put in place) only actually works on the positive case (the new auth method is available) and actually fails otherwise, so it was never working as intended 🤦‍♂️.
Took this opportunity to fix that, and make it more pythonic using exception handling instead of `hasattr()`.
Tested with multiple versions of hvac locally to ensure it worked right (we don't [yet] test multiple hvac versions in CI).
hashi_vault.py

hashi_vault - add AppRole deprecation and fix invalid deprecation logic

---

changelogs/fragments/23-hashi_vault-token_validation.yml
plugins/lookup/hashi_vault.py
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_setup.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_test.yml

Fixes #18 
The issue has most of the technical information.
The method we use to determine if a token is valid relies on the token having the ability to lookup itself. By default, all tokens inherit the "default" policy in Vault, and by default the default policy contains that capability.
However when you create a token you may request that it doesn't include the default policy. You may also modify an installation's default policy to remove this capability.
In these cases, it would be impossible to use that (perfectly valid) token with this plugin, because it would fail early attempts to validate it.
This PR adds a new option allowing you to optionally disable that early validation.
When disabled, the token will be used to query a secret without any other checks. This means that if your …

hashi_vault - enable use of tokens without lookup-self

---

changelogs/fragments/35-env-var-deprecations.yml
plugins/lookup/hashi_vault.py

Related: #10 and [Environment Variable Standardization project](https://github.com/ansible-collections/community.hashi_vault/projects/1#card-51750924).
- Add workaround for deprecations not being shown in lookups (https://github.com/ansible/ansible/issues/73051)
- Deprecate `VAULT_AUTH_METHOD` in preparation for removal in `2.0.0` (replaced by `ANSIBLE_HASHI_VAULT_AUTH_METHOD`) (#17)
- Deprecate `VAULT_TOKEN_FILE` and `VAULT_TOKEN_PATH` for removal in `2.0.0` (replaced by `ANSIBLE_HASHI_VAULT_` prefixed vars) (#15) 
- Deprecate `VAULT_SECRET_ID` and `VAULT_ROLE_ID` for removal in `2.0.0` (replaced by `ANSIBLE_HASHI_VAULT_` prefixed vars) (#20)
- Add `ANSIBLE_HASHI_VAULT_ADDR` in preparation for `VAULT_ADDR` precedence change in `1.0.0` (#8)
- Add forced `get_option` call for `secret_id` …

hashi_vault - environment variable deprecations (and one addition)

---

CHANGELOG.rst
changelogs/changelog.yaml

One of the changes points to a closed PR and not the actual PR.
Just updating the link in the changelog locations.
```paste below
```

Fix incorrect link in 0.2.0 changelog

---

changelogs/fragments/41-lower-url-env-precedence.yml
plugins/lookup/hashi_vault.py

Resolves #8 
See also #10 
With the addition of `ANSIBLE_HASHI_VAULT_ADDR` in #36 , `VAULT_ADDR` will now be used as a value of last resort, so that it does not inadvertently override an INI-specified `url` (which can still be overridden with the new env var).
This is a breaking change that is not expected to impact most users. See #8 for details on what scenarios will be impacted.
hashi_vault.py
```paste below
```

hashi_vault - lower VAULT_ADDR precedence

---

tests/integration/targets/lookup_hashi_vault/runme.sh

Resurrection of #30. Removes testing hack.
See https://github.com/ansible/ansible/pull/73000#issuecomment-757012395 for context.
CI

Remove venv testing hack

---

changelogs/fragments/41-fix-vault-addr.yml
plugins/lookup/hashi_vault.py
tests/unit/plugins/lookup/test_hashi_vault.py

Fixes #60
Related: 
- #49 
- #41 
When lowering the precedence of the `VAULT_ADDR` env var, I failed to take into account that the default value in the option itself would prevent the low pref env var value from ever being used, as implemented.
This would affect any option that has both a default value and a "low preference env var", which at the moment only applies to `url` / `VAULT_ADDR`.
This PR fixes that.
First, a unit test catching this is being added, then I will push a commit with the fix.
Note: the unit test only covers this option specifically and could be expanded. This work is actually already in progress in #59 , and I would have surfaced this eventually because of that. I'm keeping this small for this bugfix, but better tests will absolutely be introduced via the refactor. …

hashi_vault - Fix regression where VAULT_ADDR is ignored

---

codecov.yml
plugins/doc_fragments/connection.py
plugins/lookup/__init__.py
plugins/lookup/hashi_vault.py
plugins/module_utils/hashi_vault_common.py
plugins/plugin_utils/hashi_vault_plugin.py
tests/unit/plugins/base/test_hashi_vault_lookup_base.py
tests/unit/plugins/base/test_hashi_vault_plugin.py
tests/unit/plugins/module_utils/test_hashi_vault_connection_options.py
tests/unit/plugins/module_utils/test_hashi_vault_option_adapter.py
tests/unit/plugins/module_utils/test_hashi_vault_option_group_base.py

This follows on the heels of #55 , and is a little big but I'll try to break down the changes and what's happening.
The `HashiVaultOptionAdapter` class provides a consistent interface for accessing options, and lives in module_utils.
The goal is to have logic for dealing with various common options in module_utils so that it can be shared among plugins and eventually modules as well. But options are accessed differently between plugins via Config Manager and modules via AnsibleModule.
Config Manager uses a dict internally, but it's not meant to be interacted with directly. As learned from the deprecations incident and described in #35 , the ensure the best future compatibility it's best to ensure all option access goes through Config Manager's public methods, and that options aren't …

(internals) moving more functionality centrally, more tests

---

plugins/doc_fragments/68-fix-userpass-auth.yml
plugins/lookup/hashi_vault.py

Fixes #66 
Tests are going to be more work since none exist yet, tracking that in #67 .
hashi_vault
```paste below
```

hashi_vault - fix userpass auth method

---

.github/workflows/ansible-test.yml
README.md
tests/integration/targets/lookup_hashi_vault/playbooks/install_dependencies.yml
tests/unit/requirements.txt
tests/utils/constraints.txt

Somewhat related: #81
With two releases of `hvac` broken on Py2 (inadvertently), I've started thinking it's time to drop Python2 support, hence the linked issue.
This PR started as trying to fix the tests to ensure they don't use the affected versions of `hvac`, some other changes went in.
* `constraints.txt` and `requirements.txt` updated to stop at `hvac 0.10.11` in Python 2. As of this writing, `0.10.14` hasn't been released yet but it's expected it will restore Py2 compatibility. At that time I may change the constraints to exclude the two affected, and let it bring in newer ones, we'll see.
* The custom playbook for installing requirements in integration tests was not using the constraints file included in the collection. That has been changed.
* The requirements playbook's lines for …

Bunch of testing and README updates

---

tests/unit/requirements.txt
tests/utils/constraints.txt

Related: #82 
`hvac 0.10.14` (https://github.com/hvac/hvac/releases/tag/v0.10.14) was released which fixes Python 2.7 support. This updates the requirements and restraints to exclude only the broken releases, so we can again test against later releases.
We'll have to be vigilant for future breakages in `hvac` before this collection's 2.0.0 release where we'll drop support for Py2 (see #81), and in the case of another breakage, be ready to update these files again.
```paste below
```

Allow hvac 0.10.14+

---

changelogs/fragments/86-add-vars-options.yml
plugins/doc_fragments/connection.py
plugins/lookup/hashi_vault.py
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/tests.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_test.yml

Fixes #49 
Fixes #65
- `url ->`
- `ansible_hashi_vault_url`
- `ansible_hashi_vault_addr`
- `proxies -> ansible_hashi_vault_proxies`
- `namespace -> ansible_hashi_vault_namespace`
- `token -> ansible_hashi_vault_token`
- `token_validate -> ansible_hashi_vault_token_validate`
- `role_id -> ansible_hashi_vault_role_id`
- `secret_id -> ansible_hashi_vault_secret_id`
- `auth_method -> ansible_hashi_vault_auth_method`
Some new examples of usage:
```yaml
- name: use ansible vars to supply some options
vars:
ansible_hashi_vault_url: 'https://myvault:8282'
ansible_hashi_vault_auth_method: token
set_fact:
secret1: "{{ lookup('secret/data/secret1') }}"
secret2: "{{ lookup('secret/data/secret2') }}"
- name: use proxies with a dict (as direct ansible var)
vars:
ansible_hashi_vault_proxies:
http: …
```

Add ability to use ansible vars to specify options

---

tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_enable_auth.py
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_enable_engine.py
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_kv_put.py
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_policy_put.py
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_read.py
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_token_create.py
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_write.py
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_secret_id_less_setup.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_secret_id_less_test.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_setup.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/jwt_setup.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_setup.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_test.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/vault_server.yml

This PR adds several modules for use within the integration tests, replacing use of the Vault CLI (Vault binary) to configure a running Vault server, with small Python modules that use `hvac` to communicate with the server instead.
This is an important step toward making the tests be able to run against a **configurable vault target server** without needing the Vault binary available.
This will unlock wider options for being able to run the Vault test server in a container, or use a pre-running server, etc.
It also makes it easier to separate out the Vault server configuration steps into their own `setup_` targets, which is going to help a lot with improving the way tests get run and invoked, which will make testing of new plugins and modules easier.
This PR doesn't do any of that yet (I …

tests - replace use of Vault CLI to configure the Vault server

---

tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/defaults/main.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_secret_id_less_setup.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_setup.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/jwt_setup.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/tests.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_setup.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/vault_server.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/vault_server_configure.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/templates/vault_config.hcl.j2

More test improvements following on #88 
* The addresses of the vault server are now centralized into variables instead of being duplicated and spread throughout the test files. This will make it easier to specify an externally running Vault server to run tests against, furthering the separation between server prep and tests against it.
* Other variables related to configuring or starting a Vault server also moved centrally.
* The Vault server setup is now split between the acts of downloading and starting a local Vault server vs. running commands against the running Vault server (setting up backends, secrets, auth methods, etc.). Another change toward supporting a running Vault server that wasn't started by the test suite itself.
* Vault HTTP and HTTPS tests are more clearly separated …

tests - centralize vault addresses, better test control, split config vs. server start

---

tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/defaults/main.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/tests.yml

Building on #88 and #90 , this PR removed the duplicated proxy address references, and sets up the tests for working with an external tinyproxy (really any proxy I guess) rather than having the tests install and manage one.
It doesn't change the CI to use an external proxy in a container yet even though it could, because we're not yet able to use Vault in an external container, and the proxy can't reach Vault running in the test container ☹ as we have no way to address the container managed by `ansible-test` through name or IP.

tests - allow for external proxy

---

changelogs/fragments/80-add-none-auth-type.yml
plugins/lookup/hashi_vault.py
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/none_test.yml

Support the use of a locally running Vault Agent process to interact with Vault. This relieves the user almost entirely have need to manage or interact with tokens.
Fixes #79 
community.hashi_vault, authentication methods.
More details in: https://github.com/ansible-collections/community.hashi_vault/issues/79
```
- name: authenticate with vault agent
ansible.builtin.debug:
msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/hello:value', auth_method=agent, url='http://127.0.0.1:8100') }}"
```
Also related, older issue against the main Ansible repo: https://github.com/ansible/ansible/issues/60728

hashi_vault - add support for `none` auth type

---

changelogs/fragments/95-more-vars-options.yml
plugins/doc_fragments/connection.py
plugins/lookup/hashi_vault.py
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/tests.yml

Fixes: #94 
Related: #86 
Adds:
- `ansible_hashi_vault_token_path` and `ansible_hashi_vault_token_file` as requested in #94
- `ansible_hashi_vault_validate_certs`
hashi_vault.py

add more vars options (token path, token file, validate certs)

---

changelogs/fragments/97-ca_cert-env-and-vars.yml
plugins/doc_fragments/connection.py
plugins/module_utils/_hashi_vault_common.py

Fixes #75 
Adds env:
- `ANSIBLE_HASHI_VAULT_CA_CERT`
- `VAULT_CACERT` (low-precedence, see #10)
Adds vars:
- `ansible_hashi_vault_ca_cert`
Adds INI:
- `ca_cert` key in existing `lookup_hashi_vault` section.
hashi_vault

hashi_vault - add alternate methods (env, ini, vars) for `ca_cert` option

---

changelogs/fragments/96-userpass-vars-env.yml
plugins/lookup/hashi_vault.py

Fixes #54 
Note: still no tests for userpass, see #67 
Adds env:
- `ANSIBLE_HASHI_VAULT_USERNAME`
- `ANSIBLE_HASHI_VAULT_PASSWORD`
Add ansible vars:
- `ansible_hashi_vault_username`
- `ansible_hashi_vault_password`
hashi_vault
```paste below
```

hashi_vault - add env and vars for userpass options

---

plugins/doc_fragments/100-add-timeout-option.yml
plugins/doc_fragments/connection.py
plugins/module_utils/_hashi_vault_common.py
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/defaults/main.yml
tests/unit/plugins/module_utils/test_hashi_vault_connection_options.py

hashi_vault lookup - add `timeout` connection option

---

README.md
changelogs/fragments/107-deprecating-python-35.yml
tests/integration/requirements.txt
tests/unit/requirements.txt
tests/utils/constraints.txt

Related: #81 & #82
Will rebase after #106 to re-apply commits and update the new `requirements.txt` for integration tests.
* Update requirements and constraints in accordance with the recent info from `hvac` around deprecating py3.5 at the same time as py2
* Update readme to indicate py3.5 deprecation
* Add changelog fragment to ensure py3.5 deprecation gets into porting guide
```paste below
```

prepare to deprecate python 3.5

---

.github/workflows/docs.yml

So, this change enabled the docs build workflow to:
- publish the docsite to a surge.sh site !!!!
- post (and subsequently edit) a comment on the PR that links to the job run (where the artifact can be downloaded), as well a link to the surge site
On `push` (only to `main`) the surge site for main will be updated.
On a PR, the site name is dynamically generated with the PR number.
A `pull_request` event that comes from a fork (most of them, including the ones from me), doesn't have access to GitHub secrets (for the surge token), and doesn't have write access (can't post comments).
So the idea is to use `pull_request_target` which runs in the context of the base branch, and has all the permissions. One issue with this is that the default checkout won't have the changes from the PR. This is …

docs PR comments

---

.github/workflows/docs.yml

This should allow for unpublishing PR-specific docsites when the PR is closed.
As with all `pull_request_targets`, I can't test it without merging it, so this PR is here as an explanation to describe / discuss the change. Any additional direct commits related to this will be linked here.
```paste below
```

add docsite unpublish on PR close

---

.github/workflows/docs.yml

This changes the doc build to no longer be limited to PRs that change docs. The reason is that the doc build also includes plugin and module documentation changes, so we might as well ensure that all PRs have it built so we can preview those changes as well.
(no changes will be visible with this PR, will rebase #113 to test after merging)
```paste below
```

docs - have docs build on all changes

---

.github/workflows/ansible-test.yml
.github/workflows/docs.yml

GHA's MacOS is pretty flaky and times vary for a lot of things. Installing Docker can take under 2 minutes or sometimes close to 5 minutes. Other times it seemingly hangs forever, waiting for an IP assignment or some other issue.
Let's set a timeout for that step to 6 minutes, so that it'll fail (relatively) quickly, and we can restart CI.
```paste below
```

CI - set timeout on installing docker on macos

---

.github/actions/ansible-codecov/action.yml
.github/actions/ansible-codecov/process.py
.github/workflows/ansible-test.yml

Add two inputs to `ansible-codecov` action:
- `fail-on-error` -- if `'true'` it invokes `codecov` with `-Z` so that it will return an error code and fail the build in a way that's obvious. Defaults to `'true'`.
- `codecov-uploader-version` -- defaults to `latest` but can be set to a specific version so that we can pin. Since `codecov` releases new builds without changing their version number, it's difficult to tell if new errors are the result of a new build because the build number is not included in the output at all.
And then finally:
- pin our version to build ~6943~ 8278 to fix https://github.com/codecov/uploader/issues/303
```paste below
```

ci - ansible-codecov action: pin version

---

.github/workflows/docs.yml

Changes to docs build:
- a `git diff` is used to show the differences between the rendered docs in the target vs the PR, and hidden behind an expandable box (tested via #136)
- A PR that has docs changes and then doesn't have any more will not correctly unpublish the site and remove the PR comment (tested via #137)
- ^ this can happen if a PR was not rebased against a newer version of `main` that has docs changes, or can happen when changes to docs (intentional or accidental) in a PR are removed in a later commit, so that there is no longer any doc change.
```paste below
```

docs build - diff rendering and changes to changes

---

.github/actions/docker-image-versions/action.yml
.github/actions/docker-image-versions/requirements.txt
.github/actions/docker-image-versions/versions.py
.github/workflows/ansible-test.yml
README.md
docs/docsite/rst/contributor_guide.rst
docs/docsite/rst/localenv_developer_guide.rst
tests/integration/integration_config.yml.sample
tests/integration/targets/setup_localenv_docker/defaults/main.yml
tests/integration/targets/setup_vault_server_download/defaults/main.yml
tests/integration/targets/setup_vault_server_download/tasks/latest.yml
tests/integration/targets/setup_vault_server_download/tasks/main.yml

Updating the version of Vault to test against has been a manual process. I'm trying to move toward the pattern of integration tests defaulting to the latest non-prelease Version of Vault (single version) when run locally.
For CI, I'll continue testing the latest two minor versions, as described in the README (and clarified further in this PR). That's now automatic, and finding the versions is done through a custom GitHub action via a Python script, which is configurable so we can easily change which and how many versions of Vault to test against.
So the integration tests now run twice in each job, rather than being matrixed with Vault version. It removes a little bit of parallelism but I think that's a benefit because the limit of active jobs in GHA was already limiting. At least within …

Updating Vault versions in tests and CI

---

tests/integration/requirements.txt
tests/unit/requirements.txt

`hvac 0.11.1` upped the constraint for `requests` to be `>= 2.25.1`. That ends up conflicting with the constraints for `hcloud` which is pre-installed in the default test container in 2.9, causing `ansible-test` to throw an error and fail.
This PR declares `hcloud` in our requirements with a newer version. It's an unfortunate workaround, since we don't really need it at all.
Newer versions of the default container don't contain `hcloud` at all, but we'll be installing them in there anyway since we can't do this selectively.
tests/
https://github.com/hvac/hvac/pull/741

update reqirements for 2.9 hcloud hvac conflict

---

tests/integration/requirements.txt
tests/unit/requirements.txt

This reverts commit 93b38d725a83b6bd008fb1e98484b42fe51198df.
Related: 
- #145 
- https://github.com/hvac/hvac/pull/768
The change in `hvac` should not have happened in a patch release. `0.11.2` is released to address that. 
The changes may still happen in `1.0.0` so we'll need to be wary of that. For the time being though, going to revert this requirements change and deal with `1.0.0` when it comes out.
tests/
```paste below
```

Revert "update reqirements for 2.9 hcloud hvac conflict (#145)"

---

changelogs/fragments/144-deprecate-lookup-ini.yml
plugins/doc_fragments/auth.py
plugins/doc_fragments/connection.py
plugins/lookup/hashi_vault.py
tests/integration/targets/setup_vault_test_plugins/lookup_plugins/vault_test_auth.py
tests/integration/targets/setup_vault_test_plugins/lookup_plugins/vault_test_connection.py

The currently used INI section, `lookup_hashi_vault`, is specific to the `hashi_vault` lookup, but the options have all been moved to doc fragments with the intention for them to be shared collection-wide, in both modules and plugins.
To those ends, this PR:
- adds an INI section `hashi_vault_collection` that replaces `lookup_hashi_vault`
- deprecates `lookup_hashi_vault` INI section in version 3.0.0
- ensures the `lookup_hashi_vault` INI section is only valid within the `hashi_vault` lookup, and won't be inherited by new content; unfortunately to do this, I had to duplicate all the options within that plugin, including the shared INI sections. So that's going to be crappy for maintenance for a while.
- also note if a setting is set in both the `[lookup_hashi_vault]` and …

common options - change ini section, deprecate old, separate plugin doc fragments

---

.github/actions/pull-ansible-test-images/action.yml
.github/workflows/ansible-test.yml

CI updates:
- Add `stable-2.12`: https://github.com/ansible-collections/overview/issues/45#issuecomment-926783281
- Update the test image pull action to use the supported `--prime-containers` option in 2.12+: https://github.com/ansible/ansible/pull/75769
- Update all python versions in CI yaml to be strings
- Include Py `3.10` for all versions that support it
- go back to using latest codecov uploader (unpinning), now that the version numbers make sense and we can see changes in the output (https://github.com/codecov/uploader/pull/379 & https://github.com/codecov/uploader/issues/311)
CI
N/A

CI updates

---

.github/workflows/docs-full.yml
.github/workflows/docs.yml

This adds a new workflow that uses a custom github "environment" so that running this workflow requires approval.
This workflow is very similar to the existing docs build, the difference is that it uses the _entire_ PR contents, and not just the `docs/docsite`.
As described in #138 , that's a security risk when running via `pull_request_target`, because the workflow has access to secrets and an elevated GitHub token.
That's where pre-approval comes in: this workflow will not run until someone has reviewed the PR and then allows this workflow to run.
The existing docsite-only workflow will still run, automatically, so PR authors can get quick feedback on those changes, and (after review) full docs rendering that includes plugin and module doc changes is still possible before a PR is …

docs - docs-build all with approval

---

.github/workflows/ansible-test.yml
.github/workflows/docs.yml

In #150 , added concurrency settings with cancel of existing. Problem is that on merging a PR, the workflow is run twice, once for the PR close and once for the push to main; this is expected and necessary. But since the concurrency group only contains the ref, then one of those two events ends up cancelled.
Also adding a forgotten exclude so that changes to the docs full workflow don't trigger full CI.
This change includes the event name and action in the concurrency group, to ensure things work correctly.
docs
N/A

docs - fix concurrency group name

---

changelogs/fragments/172-action_group.yml
meta/runtime.yml

Adds an action group for modules in the collection. There's only 1 module right now but several others are planned.
- New Module Pull Request
runtime.yml
N/A

add action group

---

changelogs/fragments/pr-171-envvar-for-mount-point.yaml
plugins/doc_fragments/auth.py

This makes most sense; it is part of the credentials needed to
authenticate with vault, e.g. on servers with multiple independent
AppRole mountpoints.
auth methods
Hopefully self-explanatory, if it is not, please let me know.

auth: add env and ini var for mount_point option

---

README.md
changelogs/fragments/177-drop-py2-3.5.yml
tests/config.yml
tests/integration/requirements.txt
tests/requirements.yml
tests/unit/conftest.py
tests/unit/plugins/module_utils/authentication/test_hashi_vault_authenticator.py
tests/unit/plugins/module_utils/test_hashi_vault_helper.py
tests/unit/requirements.txt

Remove explicit support for Python 2.7 and 3.5 (2.6 was already unsupported).
Resolves: #81 
Not looking to explicitly break anything in those python versions, but we won't be testing against it or enforcing support in PRs. We _may_ accept PRs that look to make something that stopped working, work again in an unsupported python version, if the change is not regressive or otherwise looks reasonable. It will be a case by case basis.
N/A
N/A

Drop support for Python 2 & 3.5

---

changelogs/fragments/173-deprecated-env-vars.yml
plugins/doc_fragments/auth.py

Removes deprecated env vars for the 2.0.0 release:
- Resolves: #15 
- Resolves: #17
- Resolves: #20
auth.py
This completes the breaking changes that came from #10

remove deprecated environment variables for 2.0.0

---

codecov.yml

Addendum to #159
Adds the codecov mapping for cert auth.
~This probably will not show up in coverage on the PR; I think the XML is only used from the default branch.~ it actually did work!
- CI/coverage Pull Request
CI/coverage
N/A

add missing codecov flag file association for auth_cert

---

changelogs/fragments/190-deprecate-ansible-2.9-2.10.yml

This PR announces the deprecation of Ansible 2.9 and ansible-base 2.10 support.
Related:
- #189
- https://github.com/ansible-community/community-topics/issues/50

deprecate Ansible 2.9 and ansible-base 2.10

---

.github/workflows/ansible-test.yml
plugins/module_utils/_auth_method_jwt.py
tests/integration/targets/auth_userpass/aliases
tests/integration/targets/auth_userpass/defaults/main.yml
tests/integration/targets/auth_userpass/meta/main.yml
tests/integration/targets/auth_userpass/tasks/main.yml
tests/integration/targets/auth_userpass/tasks/userpass_setup.yml
tests/integration/targets/auth_userpass/tasks/userpass_test_controller.yml
tests/integration/targets/auth_userpass/tasks/userpass_test_target.yml
tests/unit/plugins/module_utils/authentication/fixtures/userpass_login_response.json
tests/unit/plugins/module_utils/authentication/test_auth_userpass.py

Fixes #67 
Adds unit and integration tests for the `userpass` auth method.
Also fixes a regression introduced in #191 where localenv tests don't run coverage.
auth_userpass
N/A

add userpass auth tests

---

tests/integration/targets/auth_ldap/aliases
tests/integration/targets/auth_ldap/defaults/main.yml
tests/integration/targets/auth_ldap/meta/main.yml
tests/integration/targets/auth_ldap/tasks/ldap_test_controller.yml
tests/integration/targets/auth_ldap/tasks/ldap_test_target.yml
tests/integration/targets/auth_ldap/tasks/main.yml
tests/integration/targets/setup_localenv_docker/templates/mmock/ldap_login_alt_mount.yml.j2
tests/integration/targets/setup_localenv_docker/templates/mmock/ldap_login_bad_request.yml.j2
tests/integration/targets/setup_localenv_docker/templates/mmock/ldap_login_default_mount.yml.j2
tests/unit/plugins/module_utils/authentication/fixtures/ldap_login_response.json
tests/unit/plugins/module_utils/authentication/test_auth_ldap.py

Fixes #117 
Adds unit and integration tests for the `ldap` auth method.
tests/
There have never been tests for `ldap` auth method; with the addition of MMock in #193 , we can test this in a similar way, mocking the result from Vault without having to set up an LDAP server.

Add tests for `ldap` auth method

---

.github/workflows/_shared-docs-build-push.yml

Related: #202 
The default value for the collection name didn't work on scheduled runs because it's not available. Handling via the script plugin.
docs build
```paste below
```

docs build- fix repo name on scheduled runs

---

.github/actions/docs/ansible-docs-build-html/action.yml
.github/workflows/_shared-docs-build-push.yml
.github/workflows/docs.yml

The new docs build was skipping the build step in a PR when it was closed. Because of this, it did not know whether the original PR had made docs changes or not, resulting in it always posting a comment that the "changes" had been merged.
This PR changes the behavior so that the build always runs, that way we can know whether there were changes. That makes it a bit slower, but that's hardly a concern. On a positive note, it simplifies the conditionals needed for running dependent jobs.
Also threw in another fix that should've been in #203 .
And added artifact name as an output from the build-html action'
---
Results from #204 look good for fixing change detection on closed/merged PRs and showing the appropriate message.
docs build
```paste below
```

docs build - try to fix PR closed with no change

---

codecov.yml

I think I've been using the wrong paths for the ignore section, I was trying to start them with `**/` but since the paths started in the root, I think the path fixing was trimming off the beginnings (like it was supposed to), and so the `/` part was causing them not to match... trying to see if this works.
n/a
n/a

codecov - try different path format

---

docs/docsite/extra-docs.yml
docs/docsite/rst/about_hashi_vault_lookup.rst
docs/docsite/rst/hashi_vault_lookup.rst
docs/docsite/rst/lookup_guide.rst

Adds a lookup guide to the docsite. 
This discusses topics such as:
- when to use lookups vs. modules of the same name
- the effect of lazy templating on lookup invocation
- how/when/why lookups perform writes in Vault
- the `hashi_vault` lookup and its future in the collection
~This PR also includes the changes in https://github.com/ansible-community/antsibull/pull/391 since we commit the output of `antsibull sphinx-init` in the collection (so developers can build local docs more easily and so we can slightly customize the index page).~ 
^ these changes were moved to #215 .
docsite
N/A

docs - lookup guide

---

plugins/doc_fragments/token_create.py
plugins/lookup/vault_token_create.py
plugins/modules/vault_token_create.py

Resolves #227
This doesn't really change much for the end user, it just makes an existing option use a doc fragment.
vault_token_create 
N/A

use wrapping doc fragment for `vault_token_create`

---

.github/workflows/ansible-builder.yml
.github/workflows/ansible-test.yml
.github/workflows/github-release.yml

- bump GitHub action major versions (newer Node)
- add `stable-2.13`  (https://github.com/ansible-collections/news-for-maintainers/issues/14), RIP CI execution time 😭 
- reorder Vault versions (Resolves: #225)

bump deps, add stable-2.13

---

plugins/modules/vault_write.py

In order to use the vault_write module I had to experiment for a longer time. Its nice to have such an example directly in the documentation so others could benefit.
Updated module: vault_write
none

doc: add example for write using kv v2 engine

---

plugins/doc_fragments/engine_mount.py
plugins/lookup/vault_kv1_get.py
plugins/lookup/vault_kv2_get.py
plugins/modules/vault_kv1_get.py
plugins/modules/vault_kv2_get.py
plugins/modules/vault_pki_generate_certificate.py
tests/integration/targets/lookup_vault_kv1_get/tasks/lookup_vault_kv1_get_test.yml
tests/integration/targets/lookup_vault_kv2_get/tasks/lookup_vault_kv2_get_test.yml
tests/integration/targets/module_vault_kv1_get/tasks/module_vault_kv1_get_test.yml
tests/integration/targets/module_vault_kv2_get/tasks/module_vault_kv2_get_test.yml
tests/unit/plugins/lookup/test_vault_kv1_get.py
tests/unit/plugins/lookup/test_vault_kv2_get.py
tests/unit/plugins/modules/test_vault_kv1_get.py
tests/unit/plugins/modules/test_vault_kv2_get.py

Fixes #258 
Fixes https://github.com/ansible-collections/community.hashi_vault/pull/246#discussion_r862379062
vault_kv1_get
vault_kv2_get
vault_pki_generate_certificate
The new plugins are not released yet, so there is no breaking change or changelog frragment needed.

KV get fixups

---

docs/docsite/extra-docs.yml
docs/docsite/rst/about_hashi_vault_lookup.rst
docs/docsite/rst/migration_hashi_vault_lookup.rst
plugins/lookup/hashi_vault.py

This will require (it will contain RST references to those plugins):
- #246
With the KV read content, we have full coverage of the functionality that `community.hashi_vault.hashi_vault` provided, and I can write a complete guide for making use of the newer content.

docs - `hashi_vault`  migration guide

---

changelogs/fragments/258-token_validate-default.yml
plugins/doc_fragments/auth.py
plugins/lookup/vault_login.py
plugins/module_utils/_auth_method_approle.py
plugins/module_utils/_auth_method_aws_iam.py
plugins/module_utils/_auth_method_cert.py
plugins/module_utils/_auth_method_jwt.py
plugins/module_utils/_auth_method_ldap.py
plugins/module_utils/_auth_method_none.py
plugins/module_utils/_auth_method_token.py
plugins/module_utils/_auth_method_userpass.py
plugins/module_utils/_authenticator.py
plugins/module_utils/_hashi_vault_common.py
plugins/module_utils/_hashi_vault_module.py
plugins/modules/vault_login.py
plugins/plugin_utils/_hashi_vault_plugin.py
tests/integration/targets/auth_token/tasks/token_test_controller.yml
tests/integration/targets/auth_token/tasks/token_test_target.yml
tests/unit/plugins/module_utils/authentication/conftest.py
tests/unit/plugins/module_utils/authentication/test_auth_approle.py
tests/unit/plugins/module_utils/authentication/test_auth_aws_iam.py
tests/unit/plugins/module_utils/authentication/test_auth_cert.py
tests/unit/plugins/module_utils/authentication/test_auth_jwt.py
tests/unit/plugins/module_utils/authentication/test_auth_ldap.py
tests/unit/plugins/module_utils/authentication/test_auth_none.py
tests/unit/plugins/module_utils/authentication/test_auth_token.py
tests/unit/plugins/module_utils/authentication/test_auth_userpass.py
tests/unit/plugins/module_utils/authentication/test_hashi_vault_auth_method_base.py
tests/unit/plugins/module_utils/authentication/test_hashi_vault_authenticator.py

Related: #248
Announce that the default value for `token_validate` is changing in 4.0.0.
Will repeat this PR in the release for 3.0.0 so that it's announced in the porting guide for 4.0.0 too.
I used `deprecated_features` but I don't think it's quite right. Nothing is being deprecated, just changed.
I'm trying to consider if `breaking_changes` is more appropriate, either now for the announcements, in 4.0.0 for the actual change, or even both?
`major_features` feels too major. For the actual change, `removed_features` doesn't really make sense.

implement `token_validate` default change

---

changelogs/fragments/248-token_validate-change-default.yml

Related:
- #248 
This was announced in 2.5.0, this PR is adding the announcement in 3.0.0.
- deprecation/removal

announce `token_validate` default change in 3.0.0

---

changelogs/fragments/194-remove-aws_iam_login.yml
plugins/doc_fragments/auth.py
plugins/module_utils/_authenticator.py
tests/unit/plugins/module_utils/authentication/test_hashi_vault_authenticator.py

Remove the deprecated `aws_iam_login` name for the `aws_iam` auth method.
Resolves #194 
- Deprecation/Removal

Remove `aws_iam_login` name

---

changelogs/fragments/279-incorrect-kv2-lookup-default.yml
galaxy.yml
plugins/lookup/vault_kv2_get.py

Implements the deprecation for #279 in advance of the change in 4.0.0.
vault_kv2_get

Deprecate incorrect `vault_kv2_get` lookup default

---

.github/workflows/ansible-test.yml

Resolves #283 
Confirmed macos-12 works, also confirmed that ansible-core 2.13 still doesn't work, so we'll stick to pinning at 2.12.

try macos 12

---

changelogs/fragments/289-handle-unsafe-strings.yml
plugins/module_utils/_auth_method_token.py
plugins/module_utils/_hashi_vault_common.py
tests/unit/plugins/module_utils/authentication/test_hashi_vault_auth_method_base.py
tests/unit/plugins/module_utils/test_hashi_vault_helper.py
tests/unit/plugins/plugin_utils/authentication/conftest.py
tests/unit/plugins/plugin_utils/authentication/test_auth_token.py
tests/unit/plugins/plugin_utils/test_hashi_vault_common_stringify.py
tests/unit/plugins/plugin_utils/test_hashi_vault_helper.py

Fixes #289
Right now this is only applied to the `token` but the groundwork is in place to apply this to other options as needed. 
The current issue affects things that will end up in headers, like the token.
_hashi_vault_common
- https://github.com/psf/requests/issues/6159

Fix "Unsafe" token values that originate from lookups

---

changelogs/fragments/290-retry-http-412.yml
docs/docsite/rst/user_guide.rst
plugins/module_utils/_connection_options.py

Resolves #290
Retry on HTTP status 412 for Server Side Consistent Token feature in Vault Enterprise.
_connection_options
See: 
- https://www.vaultproject.io/docs/faq/ssct#q-is-there-anything-else-i-need-to-consider-to-achieve-consistency-besides-upgrading-to-vault-1-10
- https://www.vaultproject.io/api-docs#412
Slightly related:
- #170

Add HTTP `412` to default retry list

---

changelogs/fragments/293-support-azure-auth-method.yml
codecov.yml
docs/docsite/rst/user_guide.rst
meta/ee-requirements.txt
plugins/doc_fragments/auth.py
plugins/module_utils/_auth_method_azure.py
plugins/module_utils/_authenticator.py
tests/integration/requirements.txt
tests/integration/targets/auth_azure/aliases
tests/integration/targets/auth_azure/defaults/main.yml
tests/integration/targets/auth_azure/meta/main.yml
tests/integration/targets/auth_azure/tasks/azure_test_controller.yml
tests/integration/targets/auth_azure/tasks/azure_test_target.yml
tests/integration/targets/auth_azure/tasks/main.yml
tests/integration/targets/setup_localenv_docker/templates/mmock/azure_login_alt_mount.yml.j2
tests/integration/targets/setup_localenv_docker/templates/mmock/azure_login_bad_request.yml.j2
tests/integration/targets/setup_localenv_docker/templates/mmock/azure_login_default_mount.yml.j2
tests/unit/fixtures/azure_login_response.json
tests/unit/plugins/module_utils/authentication/test_auth_azure.py
tests/unit/requirements.txt

Fixes https://github.com/ansible-collections/community.hashi_vault/issues/78
Supports 3 types of azure auth 
- use a azure access token (`jwt`) directly 
- use azure service principal
- use azure managed identity 
module_utils/_auth_method_azure.py
Currently I'm not sure how to run unit tests locally, but I verify this on my azure vm with
```
jchen@vm-vault:~$ curl -s 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F&client_id=a57bbbed-d82a-4321-9d6f-abc89542730e' -H Metadata:true | jq
{
"access_token": "[jwt]",
"client_id": "a57bbbed-d82a-4321-9d6f-abc89542730e",
"expires_in": "85943",
"expires_on": "1660545929",
"ext_expires_in": "86399",
"not_before": "1660459229",
"resource": …
```

Add support for azure auth method

---

README.md
docs/docsite/extra-docs.yml
docs/docsite/rst/CHANGELOG.rst

Since the collection's changelog is already RST, I had the idea of adding it to the docsite, so folks could more easily see the collection's changelog specifically.
Rendered:
- https://ansible-collections.github.io/community.hashi_vault/pr/299/collections/community/hashi_vault/index.html
---
I want to get feedback from the community and [DaWGs](https://github.com/ansible/community/issues/643) about:
- whether this is a good idea
- if the way I'm implementing it makes sense
- if we maybe want to provide a better/easier path for this via changes to the docs generation process
- if I've missed something entirely and the changelog is actually published on the docsite (though I would argue if so, it's been hard to find, and doing it this way will make it visible in local doc generation too)
- …

add the changelog to the collection docsite

---

docs/docsite/rst/filter_guide.rst
plugins/filter/vault_login_token.yml
plugins/lookup/vault_login.py
plugins/lookup/vault_token_create.py
plugins/modules/vault_login.py
plugins/modules/vault_token_create.py

Resolves #260 
~Also updates the committed docs build stuff (the output of `antsibull-docs sphinx-init`).~ this was moved to #306 
vault_login_token

Add docs for `vault_login_token` filter

---

changelogs/fragments/309-stringify-namespace.yml
plugins/module_utils/_hashi_vault_common.py
tests/unit/plugins/plugin_utils/authentication/test_auth_token.py
tests/unit/plugins/plugin_utils/test_hashi_vault_helper.py

Fixes #309
See also:
- #309
- #294 
- #291 
- #289 

Fix `namespace` value with newer `requests`

---

meta/runtime.yml
plugins/modules/vault_kv2_delete.py
tests/integration/targets/module_vault_kv2_delete/aliases
tests/integration/targets/module_vault_kv2_delete/meta/main.yml
tests/integration/targets/module_vault_kv2_delete/tasks/main.yml
tests/integration/targets/module_vault_kv2_delete/tasks/module_vault_kv2_delete_setup.yml
tests/integration/targets/module_vault_kv2_delete/tasks/module_vault_kv2_delete_test.yml
tests/integration/targets/setup_vault_configure/tasks/configure.yml
tests/integration/targets/setup_vault_configure/vars/main.yml
tests/integration/targets/setup_vault_test_plugins/library/vault_ci_kv2_metadata_read.py
tests/integration/targets/setup_vault_test_plugins/vars/main.yml
tests/unit/plugins/modules/test_vault_kv2_delete.py

Implementation of vault_kv2_delete module (hvac delete_latest_version_of_secret)
Fixes #300
- New Module Pull Request
vault_kv2_delete
This implements the delete latest version functionality of a KV v2 secret in Vault. This is a WIP and is missing:
- Module docs
- Integration tests

Add vault_kv2_delete module

---

changelogs/fragments/318-pki-argspec-doc-mismatch.yml
plugins/modules/vault_pki_generate_certificate.py

`vault_pki_generate_certificate` - fix argspec doc mismatch

---

changelogs/fragments/279-vault_kv2_get-lookup-mount-default.yml
plugins/lookup/vault_kv2_get.py

Fixes #279 
vault_kv2_get lookup

`vault_kv2_get` lookup - change `engine_mount_point` default to `secret`

---

changelogs/fragments/197-module-attributes.yml
plugins/doc_fragments/action_group.py
plugins/doc_fragments/attributes.py
plugins/modules/vault_kv1_get.py
plugins/modules/vault_kv2_delete.py
plugins/modules/vault_kv2_get.py
plugins/modules/vault_login.py
plugins/modules/vault_pki_generate_certificate.py
plugins/modules/vault_read.py
plugins/modules/vault_token_create.py
plugins/modules/vault_write.py

add `action_group` and `check_mode` attributes

---

tests/integration/targets/connection_options/tasks/controller.yml
tests/integration/targets/connection_options/tasks/target.yml

Tests have been failing because some combinations of controller and python versions end up installing `urllib>=2` where the proxy connection error message changed slightly. 
This is not a bug since it shouldn't have affected actual functionality, it's just the tests that were looking for a specific message.

update proxy tests for urllib>=2

---

changelogs/fragments/356-duplicate-term-options.yml
plugins/plugin_utils/_hashi_vault_lookup_base.py
tests/integration/targets/lookup_hashi_vault/tasks/lookup_test.yml
tests/unit/plugins/plugin_utils/base/test_hashi_vault_lookup_base.py

Closes #356 
See also:
- #349 
- #350 

`hashi_vault` lookup - raise exception on duplicate term string options

---

tests/unit/plugins/plugin_utils/base/test_hashi_vault_lookup_base.py

Older versions of python do not support the use of fstrings. This change replaces fstring references with a substitution.

Replace fstring in unit tests to allow testing in older versions of python

---

.github/workflows/ansible-test.yml
tests/integration/targets/setup_localenv_docker/files/requirements/constraints.txt
tests/integration/targets/setup_localenv_docker/files/requirements/requirements.txt
tests/unit/plugins/module_utils/authentication/test_auth_aws_iam.py
tests/unit/plugins/module_utils/authentication/test_auth_azure.py

CI is failing recently on local integration testing due to some dependency issues. 
`docker-compose` depends on `pyyaml<6` whose installation is broken with the newly released `cython==3`.
- https://github.com/docker/compose/issues/10836
- https://github.com/yaml/pyyaml/issues/601
Until someone fixes things in a way that doesn't require a workaround, we're putting a workaround in place.
Also took this opportunity to remove `six` and a constraint for py2.7 since we don't support it anymore.
---
Another error has been revealed: we had several instances of `assert some_mock.called_once_with(...)` which is a classic error; the method name is `assert_called_once_with` and since the mock returns a `MagicMock` for all members that don't exist, the incorrect form always asserts `True`.
It seems …

Ci/docker compose pyyaml cython -- unit mock assertions

---

changelogs/fragments/404-vault_write-spicy-keys.yml
plugins/lookup/vault_write.py
plugins/modules/vault_write.py
tests/integration/targets/lookup_vault_write/tasks/lookup_vault_write_test.yml
tests/integration/targets/module_vault_write/tasks/module_vault_write_test.yml
tests/unit/plugins/lookup/test_vault_write.py
tests/unit/plugins/modules/test_vault_write.py

`vault_write` fix ability to use `data` and `write_ttl` keys

---

.github/actions/docker-image-versions/action.yml
.github/actions/docker-image-versions/versions.py
.github/dependabot.yml
.github/workflows/ansible-builder.yml
.github/workflows/ansible-test.yml
.github/workflows/github-release.yml
README.md
changelogs/fragments/403-core-vault-python.yml
docs/docsite/rst/user_guide.rst
meta/ee-requirements.txt
meta/runtime.yml
tests/utils/constraints.txt

- Split integration matrix for Vault versions now that we have more concurrency in GHA
- Use the correct Vault docker image in integration tests
- Drop support for core 2.13
- Add support for Python 3.12
- Bump minimum `hvac` version to `1.2.1`
- Fix formatting in user guide requirements
- Bump actions/checkout to v4 and disable git progress
- Update release workflow to support galaxy v3
- Update readme
- Add dependabot.yml

v6 changes: split Vault testing, drop core 2.13, add py3.12, bump hvac minimum, add dependabot, more small changes

---

.github/workflows/ansible-test.yml

When dependabot opens a PR or updates its PR branch, it triggers CI for both the push and the PR, since the branch is local to repository.
This PR tries to ignore those branch pushes so only the PR trigger goes off.

ignore pushes on dependabot branches

---

.github/workflows/ansible-test.yml

The local integration runs are the longest in the CI, since they run the full integration suite 3 times.
The idea is to ensure that integration tests still work properly in multiple runs against the same running Vault containers. Many of the integration tests have setup/teardown code that by our convention, must be idempotent. Many of them also use an optimization whereby they write a canary value to a cubbyhole, and if that value exists, the setup code is skipped, which saves a little bit of time.
So in CI, we run a normal "first run", a second run against the same containers (should skip setup code where canary values are found), and then a third run where we delete the cubbyhole canary values to ensure that the setup code is actually idempotent regardless of the canary values.
We run …

make local integration faster

---

changelogs/fragments/429-add-cert-auth-variables.yml
plugins/doc_fragments/auth.py

This PR adds option to set the cert_auth_public_key and cert_auth_private_key parameters using the variables ansible_hashi_vault_cert_auth_public_key and ansible_hashi_vault_cert_auth_private_key.
Since AWX does not permit setting environment variables with the `ANSIBLE_` prefix, this will help to use those variables instead.
Resolves #428 
hashi_vault lookup
```paste below
cert_auth_public_key:
env:
- name: ANSIBLE_HASHI_VAULT_CERT_AUTH_PUBLIC_KEY
vars:
- name: ansible_hashi_vault_cert_auth_public_key
ini:
- section: hashi_vault_collection
key: cert_auth_public_key
cert_auth_private_key:
env:
- name: ANSIBLE_HASHI_VAULT_CERT_AUTH_PRIVATE_KEY
vars:
- name: ansible_hashi_vault_cert_auth_private_key
ini:
- section: hashi_vault_collection
key: cert_auth_private_key
```

Adding variables for cert_auth_public and private params

---

.github/workflows/docs-push.yml
.github/workflows/docs.yml

Surge docs push is failing with invalid token. We've only been linking to the GH pages version of the docsite for years now anyway and I don't want to figure out what's wrong with surge.

disable surge docs push

---

tests/integration/targets/auth_cert/tasks/cert_test_controller.yml
tests/integration/targets/auth_cert/tasks/cert_test_target.yml

Vault 1.18 has updated it's exception string therefor the integration tests for hashi_vault are now failing.
This pull request fixes the integration test failure.
- auth_cert
https://github.com/hashicorp/vault/compare/v1.17.6...v1.18.0# has the following change in file `builtin/credential/cert/path_login.go`
```
+ const certAuthFailMsg = "failed to match all constraints for this login certificate"
...
- return nil, logical.ErrorResponse(fmt.Sprintf("invalid certificate or no client certificate supplied; additionally got errors during verification: %v", retErr)), nil
+ return nil, logical.ErrorResponse(fmt.Sprintf("%s; additionally got errors during verification: %v", certAuthFailMsg, retErr)), nil
```
```paste below
```

Vault 1.18 has a new exception response string

---

.github/workflows/ansible-test.yml

The plural form has been removed from ansible-core devel. The singluar form has been present since ansible-base 2.10.
Ref: https://forum.ansible.com/t/couldnt-resolve-module-action-community-crypto-openssl-privatekey-only-with-ansible-core-devel/10711/2
GHA CI

CI: switch to non-deprecated singular form
