README.md
plugins/lookup/hashi_vault.py

- Removes `version_added` entries
- Fixes up some wording and documentation
- Adds required `hvac` version for JWT to docstring and readme
- Shorten examples to under 160 chars
hashi_vault.py

Update hashi_vault docstrings, examples, requirements

---

tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml
tests/integration/targets/lookup_hashi_vault/runme.sh

Following up on this conversation: https://github.com/ansible-collections/community.hashi_vault/pull/3#discussion_r532811284
- CI

Use conditional interpreter for package module in CI

---

README.md

Add an FAQ section to README and cover some topics around the collection's name and content that have come up a few times in IRC.

Add FAQ to README

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/0.1.0.yml
galaxy.yml

Release 0.1.0

---

galaxy.yml

Next expected version is [v1.0.0](https://github.com/ansible-collections/community.hashi_vault/milestone/2).

1.0.0 next expected release

---

.github/workflows/github-release.yml

Adding a little GH action to make GH releases
Note: this first pass does not create the release, it's to test the steps and description output.
Need to merge to  main for the workflow to show up, then future changes can be tested from branches.
```paste below
```

First pass at GH release automation

---

.github/workflows/ansible-test.yml

- Tweak the vault caching and cache key
- Download `community.crypto` from GitHub instead of Galaxy (https://github.com/ansible/galaxy/issues/2302)
- Cache the latest version as well so we're not checking it out 50+ times per run
```paste below
```

CI - more caching: community.crypto and some vault caching tweaks

---

tests/integration/targets/lookup_hashi_vault/runme.sh

Improve the comment from #45.
tests/integration/targets/lookup_hashi_vault/runme.sh

Improve venv setup comment

---

.github/workflows/ansible-test.yml

Enable a scheduled CI run once a day at UTC 14:00
```paste below
```

Add scheduled CI run

---

galaxy.yml

Version 1.1.0 next expected release

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/1.1.0.yml
changelogs/fragments/50-add-proxies-option.yml

- Release
- 
```paste below
```

Release 1.1.0

---

.github/workflows/ansible-test.yml

Re: https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100
Ensure we test against 2.11-stable and the new devel (2.12)
```paste below
```

run CI against Ansible 2.12/stable-2.11

---

changelogs/fragments/81-deprecating-python2.yml

Adding a changelog fragment for the upcoming py2 deprecation (#81) so that notice goes out earlier.

deprecate python2 in changelog

---

.github/workflows/ansible-test.yml
tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/defaults/main.yml

Update to Vault 1.7.3 as the latest version used in tests.
```paste below
```

tests - update Vault to 1.7.3

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/1.3.1.yml
docs/docsite/extra-docs.yml
galaxy.yml

Fix docsite and release 1.3.1
```paste below
```

Release 1.3.1

---

.github/workflows/ansible-test.yml

Update codecov action to v2
See also: 
- https://github.com/codecov/codecov-action#%EF%B8%8F--deprecration-of-v1
- https://github.com/codecov/codecov-action/pull/392
- https://docs.codecov.com/docs/about-the-codecov-bash-uploader
- https://docs.codecov.com/docs/codecov-uploader
```paste below
```

CI - update codecov action to v2

---

galaxy.yml
plugins/lookup/hashi_vault.py

- Update attribution of original author to reflect new contact information.
@juliedavila GitHub won't let me explicitly request you for review, but would you mind taking a look and adding an approval review if this looks right?

update attribution with new contact info

---

.github/workflows/docs.yml

Related: #120 & #121
Trying to ensure the publish part doesn't run if the secret is not available.
Also updated the PR comments.
```paste below
```

fix fork pushes

---

docs/docsite/rst/contributor_guide.rst

This is both a real PR/fix:
- Fix indented bulleted list in contributor guide
As well as a proof of concept test for several PRs (can not test `pull_request_target` workflow in the PR that introduced it):
- #120
- #122 
- #123 
```paste below
```

docs - fix bulleted list in contributor guide

---

.github/workflows/docs.yml

Trying out a change where docs are not published and no PR comment is made if there is no actual change in docsite contents.
As with all `pull_request_target` changes, this will be merged and tested with other PRs. Additional direct commits needed to fix anything with be linked here.
```paste below
```

docsbuild - no publish on no change

---

docs/docsite/rst/contributor_guide.rst

Update the Contribution Guide for docs submissions.
```paste below
```

docs - update docs contribution instructions

---

docs/preview/.gitignore
docs/preview/build.sh
docs/preview/conf.py
docs/preview/requirements.txt

Update the docs build to use the ansible theme!
`docs/preview/`
docsite build was originally set up before the ansible theme could be used.

use ansible theme for docs

---

.github/workflows/ansible-test.yml

Adding coverage to sanity
~DO NOT MERGE until  https://github.com/ansible/ansible/issues/75647 is resolved (right now 2.9 sanity is disabled in this PR to workaround that).~
2.9 issue mitigated in https://github.com/ansible/ansible/pull/75651
coverage
N/A

CI - sanity coverage

---

docs/docsite/rst/contributor_guide.rst

Update contributor guide wording.
docsite
N/A

docsite - update contributor guide

---

.github/actions/macos-docker/action.yml
.github/workflows/ansible-test.yml

Docker on MacOS recently started failing:
> (default) Found a new host-only adapter: "vboxnet0"
> Error creating machine: Error in driver during machine creation: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
> VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
> VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp
> 
Other issues in other CI that use RHEL also had an issue, which was solved by explicitly including `iptables` as a dependency, but I don't see how/where that make a difference here.
~The only thing I could find that differed between …

fix macos docker in CI

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/1.5.0.yml
changelogs/fragments/172-action_group.yml
changelogs/fragments/pr-171-envvar-for-mount-point.yaml

- Release Pull Request
N/A
N/A

Release 1.5.0

---

changelogs/fragments/176-url-is-required.yml
plugins/doc_fragments/connection.py
plugins/module_utils/_connection_options.py
plugins/module_utils/_hashi_vault_common.py
tests/unit/plugins/lookup/test_hashi_vault.py
tests/unit/plugins/module_utils/test_hashi_vault_connection_options.py

Resolves: #83 
connection_options
N/A

connection options - make `url` required and remove the default value

---

.github/workflows/docs-full.yml
.github/workflows/docs.yml

Fixes #182 
(CI on this PR will not be helpful, will open test PRs against the branch)
docs build
N/A

docs build - try head_ref to fix concurrency issues

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/173-deprecated-env-vars.yml
changelogs/fragments/176-url-is-required.yml
changelogs/fragments/177-drop-py2-3.5.yml
changelogs/fragments/2.0.0.yml
galaxy.yml

Release 2.0.0
- Release Pull Request

Release 2.0.0

---

.github/actions/ansible-codecov/action.yml
.github/workflows/ansible-test.yml

Fixes #180 
Note: the schedule changes won't be testable in this PR (other than syntax), so will have to wait for the next scheduled run to ensure they worked completely.
CI/coverage
See #180

Reduce codecov flags

---

docs/docsite/rst/contributor_guide.rst

Provides guidance for contributing new auth methods
docs/

docs - contributing auth methods

---

.github/actions/docs/ansible-docs-build-diff/action.yml

Used the wrong core method.
Error demonstrated here: https://github.com/ansible-collections/community.docker/runs/4680987977?check_suite_focus=true
```paste below
```

fix truncation notice in docs build

---

plugins/lookup/vault_read.py

Fixes typo in examples section
vault_read
```paste below
```

Fix typo in example section of vault_read

---

.github/workflows/docs-push.yml
.github/workflows/docs.yml

Fixes #219
Also uses ansible-core `devel` for docs build.
docs-build

fix docs build PR comment main link, use `devel`

---

docs/docsite/links.yml

add extra-links config

---

plugins/module_utils/_auth_method_approle.py
plugins/module_utils/_auth_method_aws_iam.py
plugins/module_utils/_auth_method_jwt.py
plugins/module_utils/_auth_method_ldap.py
plugins/module_utils/_auth_method_none.py
plugins/module_utils/_auth_method_token.py
plugins/module_utils/_auth_method_userpass.py
plugins/module_utils/_authenticator.py
plugins/module_utils/_connection_options.py
plugins/module_utils/_hashi_vault_common.py

update supported python versions in private utils

---

.github/workflows/ansible-test.yml
README.md
changelogs/fragments/189-remove-ansible-2_9-2_10-support.yml
meta/runtime.yml
tests/unit/plugins/lookup/test_vault_ansible_settings.py

Resolves #189 
- deprecation/removal

Remove ansible 2.9 and 2.10 support

---

.github/workflows/ansible-test.yml

Addresses: 
- https://github.com/ansible-collections/news-for-maintainers/issues/18
And the resulting CI failures happening today due to that.

update python versions in CI

---

changelogs/fragments/301-orphan-token-handling.yml
plugins/doc_fragments/token_create.py
plugins/lookup/vault_token_create.py
plugins/modules/vault_token_create.py
tests/integration/targets/lookup_vault_token_create/tasks/lookup_vault_token_create_test.yml
tests/integration/targets/module_vault_token_create/tasks/module_vault_token_create_test.yml
tests/integration/targets/setup_vault_configure/vars/main.yml
tests/unit/plugins/lookup/test_vault_token_create.py
tests/unit/plugins/modules/test_vault_token_create.py

Fixes #301 
vault_token_create

`vault_token_create` -- use new hvac method

---

.github/actions/docker-image-versions/versions.py
.github/workflows/ansible-builder.yml
.github/workflows/ansible-test.yml
.github/workflows/github-release.yml

replace set-output in workflows

---

changelogs/fragments/248-token_validate-default.yml
plugins/doc_fragments/auth.py
plugins/lookup/vault_login.py
plugins/module_utils/_auth_method_token.py
plugins/module_utils/_authenticator.py
plugins/modules/vault_login.py
tests/integration/targets/auth_token/tasks/token_test_controller.yml
tests/integration/targets/auth_token/tasks/token_test_target.yml
tests/integration/targets/lookup_hashi_vault/tasks/lookup_test.yml
tests/integration/targets/lookup_vault_kv1_get/tasks/lookup_vault_kv1_get_test.yml
tests/integration/targets/lookup_vault_kv2_get/tasks/lookup_vault_kv2_get_test.yml
tests/integration/targets/lookup_vault_read/tasks/lookup_vault_read_test.yml
tests/integration/targets/lookup_vault_write/tasks/lookup_vault_write_test.yml
tests/integration/targets/module_vault_kv1_get/tasks/module_vault_kv1_get_test.yml
tests/integration/targets/module_vault_kv2_delete/tasks/module_vault_kv2_delete_test.yml
tests/integration/targets/module_vault_kv2_get/tasks/module_vault_kv2_get_test.yml
tests/integration/targets/module_vault_read/tasks/module_vault_read_test.yml
tests/integration/targets/module_vault_token_create/tasks/module_vault_token_create_test.yml
tests/integration/targets/module_vault_write/tasks/module_vault_write_test.yml
tests/unit/plugins/module_utils/authentication/test_auth_token.py

update `token_validate` default value from `true` to `false`

---

changelogs/fragments/324-deprecate-hvac.yml
changelogs/fragments/340-deprecate-core-211-212.yml

Add deprecation changelog notices for:
- #324 
- #340 
- 

add deprecation notices

---

.github/actions/docker-image-versions/versions.py
plugins/lookup/vault_login.py
plugins/lookup/vault_token_create.py
plugins/modules/vault_login.py
tests/unit/compat/builtins.py
tests/unit/compat/mock.py
tests/unit/plugins/lookup/conftest.py
tests/unit/plugins/module_utils/authentication/test_auth_none.py
tests/unit/plugins/module_utils/authentication/test_auth_token.py
tests/unit/plugins/module_utils/authentication/test_hashi_vault_authenticator.py
tests/unit/plugins/module_utils/test_hashi_vault_helper.py

Fixes: #344 (?)
Fixes new sanity unused import failure:
- https://github.com/ansible-collections/news-for-maintainers/issues/34

fix new sanity test requirements and CI docker version hang

---

plugins/lookup/vault_write.py
plugins/modules/vault_kv2_delete.py
plugins/modules/vault_kv2_get.py
plugins/modules/vault_kv2_write.py

Extends:
- #348 
Adding some `seealso` links that I didn't think about before merging
vault_kv2_write
cc @devon-mar

add some seealso links for vault_kv2_write

---

.github/workflows/ansible-test.yml
README.md

Related:
- https://github.com/ansible-collections/news-for-maintainers/issues/41

update CI for ansible-core 2.15 and python 3.11

---

plugins/modules/vault_kv2_write.py

Fixes #362 
Also add examples for how to patch with multiple tasks.
vault_kv2_write

update `vault_kv2_write` to clarify patch operations

---

.github/workflows/ansible-test.yml
README.md
changelogs/fragments/340-drop-core-211-212.yml
meta/runtime.yml
tests/integration/requirements.txt
tests/unit/plugins/lookup/test_vault_token_create.py
tests/unit/plugins/module_utils/authentication/test_auth_token.py
tests/unit/requirements.txt
tests/utils/constraints.txt

Closes #340
- CI/core change Pull Request

drop `ansible-core` 2.11 & 2.12

---

changelogs/fragments/324-minimum-hvac-version.yml
docs/docsite/rst/user_guide.rst
tests/utils/constraints.txt

Closes #324 
- Requirements Pull Request

Set minimum `hvac` version

---

plugins/lookup/vault_token_create.py
tests/integration/targets/auth_approle/tasks/approle_test_target.yml
tests/integration/targets/auth_approle/tasks/main.yml
tests/integration/targets/auth_aws_iam/tasks/aws_iam_test_target.yml
tests/integration/targets/auth_aws_iam/tasks/main.yml
tests/integration/targets/auth_azure/tasks/azure_test_target.yml
tests/integration/targets/auth_azure/tasks/main.yml
tests/integration/targets/auth_cert/tasks/cert_test_target.yml
tests/integration/targets/auth_cert/tasks/main.yml
tests/integration/targets/auth_jwt/tasks/jwt_test_target.yml
tests/integration/targets/auth_jwt/tasks/main.yml
tests/integration/targets/auth_ldap/tasks/ldap_test_target.yml
tests/integration/targets/auth_ldap/tasks/main.yml
tests/integration/targets/auth_token/tasks/main.yml
tests/integration/targets/auth_token/tasks/token_test_controller.yml
tests/integration/targets/auth_token/tasks/token_test_target.yml
tests/integration/targets/auth_userpass/tasks/main.yml
tests/integration/targets/auth_userpass/tasks/userpass_test_target.yml
tests/integration/targets/connection_options/tasks/controller.yml
tests/integration/targets/connection_options/tasks/target.yml
tests/integration/targets/module_vault_login/tasks/module_vault_login_test.yml
tests/integration/targets/setup_localenv_docker/files/playbooks/vault_docker.yml
tests/integration/targets/setup_localenv_docker/tasks/main.yml
tests/integration/targets/setup_localenv_gha/files/playbooks/gha.yml

Docs and other things are already up to standard.
Changed tests to comply with this.
Resolves #357

Changed all truthy values to true/false

---

.github/workflows/ansible-test.yml
changelogs/fragments/381-localenv_docker.yml
tests/integration/targets/setup_localenv_docker/defaults/main.yml
tests/integration/targets/setup_localenv_docker/templates/docker-compose.yml.j2

update localenv docker for container image parameterization and update vault source

---

.github/workflows/ansible-test.yml

bump CI python to 3.10
See:
- https://github.com/ansible-collections/news-for-maintainers/issues/49

bump CI python to 3.10

---

.github/workflows/ansible-test.yml
README.md

add core 2.16 to CI

---

tests/unit/plugins/modules/test_vault_pki_generate_certificate.py

Fix type check causing failing sanity tests

fix unidiomatic type check

---

tests/integration/targets/auth_approle/tasks/approle_test_controller.yml
tests/integration/targets/auth_approle/tasks/approle_test_target.yml

- https://github.com/ansible-collections/community.hashi_vault/actions/runs/6812856300/job/18527155295#step:11:1149
Vault changed some error messages:
- https://github.com/hashicorp/vault/commit/87376a1f5c676c9a54e1050b3e71e32c4ac92595

update vault responses in tests

---

.github/actions/ansible-codecov/process.py
.github/workflows/ansible-test.yml
tests/integration/targets/setup_localenv_docker/files/requirements/constraints.txt
tests/integration/targets/setup_localenv_docker/files/requirements/requirements.txt
tests/integration/targets/setup_localenv_docker/files/requirements/requirements.yml
tests/integration/targets/setup_localenv_docker/tasks/docker.yml
tests/integration/targets/setup_localenv_docker/templates/docker-compose.yml.j2

- change the docker localenv to use docker compose v2, removing the dependency on python docker libraries
- update our codecov action to sleep and retry on issues with codecov's tokenless uploads from forks
- https://github.com/codecov/feedback/issues/301

fix local integration tests

---

.github/workflows/ansible-test.yml
.github/workflows/docs-push.yml
.github/workflows/docs.yml
tests/integration/targets/setup_localenv_docker/README.md
tests/integration/targets/setup_localenv_docker/tasks/main.yml
tests/integration/targets/setup_localenv_gha/README.md
tests/integration/targets/setup_localenv_gha/templates/launch.sh.j2
tests/unit/plugins/lookup/test_vault_ansible_settings.py
tests/unit/plugins/module_utils/test_hashi_vault_connection_options.py

CI is currently failing, and doesn't test against stable-2.17 and stable-2.18.
various

Fix CI, add stable-2.17 and stable-2.18 to CI

---

.github/workflows/ansible-test.yml
tests/integration/targets/auth_approle/tasks/approle_test_controller.yml
tests/integration/targets/module_vault_database_static_role_create/tasks/module_vault_database_static_role_create_test.yml
tests/unit/plugins/module_utils/option_adapter/test_hashi_vault_option_adapter.py
tests/unit/plugins/module_utils/test_hashi_vault_module.py
tests/unit/plugins/modules/conftest.py
tests/unit/plugins/modules/test_vault_pki_generate_certificate.py

Fix tests to work with Ansible 2.19
Closes: #464 
- Tests/CI Pull Request

Tests/fix various issues 2.19

---

.github/workflows/ansible-builder.yml
.github/workflows/ansible-test.yml
.github/workflows/github-release.yml
README.md
changelogs/fragments/470-core-python-versions.yml
galaxy.yml
meta/runtime.yml
plugins/module_utils/_auth_method_approle.py
plugins/module_utils/_auth_method_aws_iam.py
plugins/module_utils/_auth_method_azure.py
plugins/module_utils/_auth_method_jwt.py
plugins/module_utils/_auth_method_ldap.py
plugins/module_utils/_auth_method_none.py
plugins/module_utils/_auth_method_token.py
plugins/module_utils/_auth_method_userpass.py
plugins/module_utils/_authenticator.py
plugins/module_utils/_connection_options.py
plugins/module_utils/_hashi_vault_common.py
tests/config.yml
tests/unit/conftest.py
tests/unit/plugins/modules/test_vault_token_create.py

Remove support for old core & python versions
